# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("get_empirical_pmf", {
    # WriteMe
    expect_true(TRUE)
})

test_that("get_empirical_intensity", {
    # WriteMe
    expect_true(TRUE)
})
