# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Earthquake occurrence dataset
#' @rdname data
#' 
#' @description
#' Earthquake occurrence in several locations in Turkey and neighboring regions 
#' of Greece, recorded between January 2013 and January 2023.
#' 
#' @details
#' The data were obtained from the Kandilli Observatory and Earthquakes 
#' Research Institute at Boğaziçi University. The dataset comprises earthquake 
#' occurrences in Turkey and neighboring regions of Greece, recorded between 
#' January 2013 and January 2023, spanning 1181 cities. In recent years, the 
#' Gulf of Gökova in Southwest Turkey has witnessed two significant seismic 
#' events: the Bodrum earthquake on July 20, 2017 (magnitude 6.6, also felt on 
#' the Greek island of Kos), and the Aegean Sea earthquake on 
#' November 1st, 2020, with a moment magnitude of 7.0 (the highest magnitude 
#' observed during the period).
#' 
#' Only the records for the 195 cities that experienced more than two 
#' earthquakes over the specified period are available in this dataset.
#'
#' **Important:** per its original licensing, this dataset should be used 
#' only for scientific and non-commerical purposes. Upon use of this dataset, 
#' proper attribution should be given to B.U. KOERI-RETMC (Boğaziçi University  
#' Kandilli Observatory and Earthquake Research Institute - Regional 
#' Earthquake-Tsunami Monitoring Center) in scientific articles and general 
#' purpose reports by referencing the KOERI Catalog citation.
#'
#' @format ## `earthquake`
#' A list containing vectors of earthquake occurrence date for 195 locations.
#'
#' @source B.U. KOERI-RETMC (Boğaziçi University Kandilli Observatory and 
#' Earthquake Research Institute - Regional Earthquake-Tsunami Monitoring 
#' Center) <http://www.koeri.boun.edu.tr/sismo/2/earthquake-catalog/>
#' 
#' @examples
#' head(earthquake)
"earthquake"
