# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Empirical intensity function
#'
#' 
#' @description
#' Compute the empirical intensity for each realization of the point process.
#' 
#' @details
#' The empirical intensity values for each indidividual point process 
#' realization are computed along the union of all individual point process 
#' occurrences.
#' 
#' See Picard et al (2024) or the tutorial vignette "PCA for Point Processes 
#' with Earthquake Data" for more details:
#' `vignette("01-introduction-pppca", package = "pppca")`
#' 
#' @references
#' Picard, Franck, Vincent Rivoirard, Angelina Roche, and Victor 
#' Panaretos. 2024. “PCA for Point Processes.” arXiv. 
#' \doi{10.48550/arXiv.2404.19661}.
#' 
#' @seealso [pppca::get_empirical_pmf()]
#'
#' @inheritParams pppca
#' @inheritParams parallel::mclapply
#'
#' @return List of empirical intensity values for each individual point
#' process realization passed in input.
#' @export
#' 
#' @importFrom parallel mclapply
#' @importFrom parallelly availableCores
#'
#' @examples
#' emp_int <- get_empirical_intensity(earthquake)
get_empirical_intensity <- function(
        PP, mc.cores = parallelly::availableCores()) {
    pmf <- get_empirical_pmf(PP)
    int <- mclapply(pmf, FUN = function(x){diff(x)}, mc.cores = mc.cores)
    return(int)
}

#' Empirical cumulative probability mass function
#'
#' 
#' @description
#' Compute the empirical cumulative mass function (PMF) for each realization of 
#' the point process.
#' 
#' @details
#' The empirical cumulative PMF values for each indidividual point process 
#' realization are computed along the union of all individual point process 
#' occurrences.
#' 
#' See Picard et al (2024) or the tutorial vignette "PCA for Point Processes 
#' with Earthquake Data" for more details:
#' `vignette("01-introduction-pppca", package = "pppca")`
#' 
#' @references
#' Picard, Franck, Vincent Rivoirard, Angelina Roche, and Victor 
#' Panaretos. 2024. “PCA for Point Processes.” arXiv. 
#' \doi{10.48550/arXiv.2404.19661}.
#' 
#' @seealso [pppca::get_empirical_intensity()]
#'
#' @inheritParams pppca
#' @inheritParams parallel::mclapply
#'
#' @return List of empirical cumulative PMF values for each individual point
#' process realization passed in input.
#' @export
#' 
#' @importFrom parallel mclapply
#' @importFrom parallelly availableCores
#'
#' @examples
#' emp_pmf <- get_empirical_pmf(earthquake)
get_empirical_pmf <- function(PP, mc.cores = parallelly::availableCores()) {
    n <- length(PP)
    grid <- sort(unique(Reduce('c', PP)))
    PPbin <- mclapply(PP, grid, FUN = function(x, gg) {	
        y <- rep(0, length(gg))
        y[which(gg %in% x)] <- 1
        return(y)
    }, mc.cores = mc.cores)
    pmf <- mclapply(PPbin, FUN = function(x) {
        return(cumsum(x)[-1])
    }, mc.cores = mc.cores)
    return(pmf)
}
