# WARNING - Generated by {fusen} from dev/flat_internal.Rmd: do not edit by hand

#' Build predicted PMF
#'
#' @keywords internal
#' 
#' @description Build individual predicted PMF from Karhunen–Loève 
#' decomposition
#' @details
#' The Principal Component Analysis for Point Process data is based on the 
#' Karhunen–Loève decomposition of the empirical *cumulative mass functions*.
#' 
#' See Picard et al (2024) or the tutorial vignette "PCA for Point Processes 
#' with Earthquake Data" for more details:
#' `vignette("01-introduction-pppca", package = "pppca")`
#'
#' @param i integer, indivdiual index.
#' @param baseline_pmf numerical vector containing the values for the 
#' baseline for PMF prediction.
#' @param eigenval numerical vector containing eigenvalues for each principal 
#' component.
#' @param scores data frame of individual scores (in rows) for each principal 
#' component (in columns).
#' @param eigenfun data frame containing the values of the eigenfunctions for 
#' each principal components (in columns) over the occurrence `grid` 
#' (in rows).
#'
#' @return numerical vector containing the values for the predicted PMF 
#' function.
#' @export
#'
build_predicted_pmf <- function(i, baseline_pmf, eigenval, scores, eigenfun) {
    J <- dim(eigenfun)[2]
    w <- baseline_pmf
    for (j in 1:J) {
        w <- w + sqrt(eigenval[j]) * scores[i,j] * eigenfun[,j]
    }
    return(w)
}
