# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' @name pppca-package
#' @rdname pppca-package
#' @title Point Process Principal Component Analysis
#' 
#' @description
#' Principal Component Analysis (PCA) for dimension reduction and variance 
#' decomposition of point process data
#' 
#' @details
#' The Principal Component Analysis for Point Process data is based on the 
#' Karhunen–Loève decomposition of the empirical *cumulative mass functions*.
#' 
#' See Picard et al (2024) or the tutorial vignette "PCA for Point Processes 
#' with Earthquake Data" for more details:
#' `vignette("01-introduction-pppca", package = "pppca")`
#' 
#' @author
#' - Franck Picard ([link](https://franckpicard.github.io/)|
#'   [ORCID](https://orcid.org/0000-0001-8084-5481))
#' - Ghislain Durif ([link](https://gdurif.perso.math.cnrs.fr/)|
#'   [ORCID](https://orcid.org/0000-0003-2567-1401))
#'
#' @references
#' Picard, Franck, Vincent Rivoirard, Angelina Roche, and Victor 
#' Panaretos. 2024. “PCA for Point Processes.” arXiv. 
#' \doi{10.48550/arXiv.2404.19661}.
"_PACKAGE"
